import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "sonner";
import MobileNavbar from "@/components/mobile_navbar/MobileNavbar";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { LanguageProvider } from "@/components/language-provider";

export const metadata: Metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const messages = await getMessages();

  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body>
        {/* <NextIntlClientProvider > */}
            <LanguageProvider>
          <Navbar />
          <MobileNavbar />

          <main>{children}</main>

          <Footer />

          <Toaster richColors position="top-right" />
            </LanguageProvider>
        {/* </NextIntlClientProvider> */}

      </body>
    </html>
  );
}